### ISSUE TITLE
Google Drive desktop app for macOS is interfering with OpenMTP

### ISSUE THREAD

**Issue by ganeshrvel** [ganeshrvel/openmtp#245]
[Google Drive desktop](https://support.google.com/drive/answer/7329379#zippy=%2Cdownload-install-google-drive-for-desktop) app for macOS is interfering with OpenMTP. 

The Google Drive desktop app is currently in beta and it has been messing up with MTP operations.

Solution: Quit any instances of Googles Drive desktop or Backup and Sync from the menu bar.

**Comment by justinpenner** [comment]
The [new Google Drive app](https://support.google.com/drive/answer/7329379) (formerly two separate apps: Drive File Stream and Backup & Sync – I was using the latter) is out of beta and I switched over to it a few weeks ago. I'm not seeing any interference with OpenMTP, although I'm not sure exactly what bug to look for. I'm running Google Drive 53.0.8.0 (Intel).

**Comment by ganeshrvel** [comment]
@justinpenner I am getting more reports that Google drive and Dropbox apps are interfering with the OpenMTP's USB read access. Completely quitting these apps fixes this issue.

**Comment by t1956om** [comment]
How can I quit Google Drive?

**Comment by dimitrid** [comment]
Quitting google drive worked for me.

Running macos 13.5 and Google Drive Version: 80.0.1.0 (Apple Silicon)

**Comment by dpkingston** [comment]
Android 14 and MacOS Sonoma 14.6.1
I still see the issue that OpenMTP cannot connect to the Android device over USB if Google Drive (99.0.0.0) is running.
I quit Google Drive and then refreshed OpenMTP and it works.
I restarted Google Drive and OpenMTP **continued** working!
Quit and restarted OpenMTP.

It connected and ran fine.  Don't know how they are interacting but its reasonably straightforward to get them working without having to live without Drive (which I depend on).

Ganesh, do you have some insight as to what is happening here?

**Comment by ganeshrvel** [comment]
If you’re on macOS Sonoma (the latest build), when you launch Google Drive and try to plug in your phone, the OS will prompt you to grant Google Drive USB access. Simply deny the request. That should fix the issue.

**Comment by acetriper** [comment]
> If you’re on macOS Sonoma (the latest build), when you launch Google Drive and try to plug in your phone, the OS will prompt you to grant Google Drive USB access. Simply deny the request. That should fix the issue.
> 
> [@dpkingston](https://github.com/dpkingston)

it still doesnt work after the phone is on the not sync not backup list. only after quitting drive completely it works. (mac tahoe)

**Comment by cchanche** [comment]
The error screen mentioning to quit these apps has been useful to me 👍 

Stopping by to mention that I have had to qui the macOS "Photos" app as well. In my case, the app was seeing my android device (a Polar sports watch) as a device to scan for pictures.

Hope it helps
